using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;



namespace System.Runtime.CompilerServices
{
    internal class IsExternalInit { }
}

namespace ShadedCanopy.Gen
{
    [Generator(LanguageNames.CSharp)]
    public sealed class AutoGenMembersGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var memberAccesses = context.SyntaxProvider.CreateSyntaxProvider(
                    static (node, _) => node is MemberAccessExpressionSyntax,
                    static (ctx, _) =>
                    {
                        var mae = (MemberAccessExpressionSyntax)ctx.Node;
                        if (mae.Name is not IdentifierNameSyntax name) return null;

                        var semanticModel = ctx.SemanticModel;

                        var leftSymbol = semanticModel.GetSymbolInfo(mae.Expression).Symbol;
                        var leftType = leftSymbol as INamedTypeSymbol
                                       ?? (semanticModel.GetTypeInfo(mae.Expression).Type as INamedTypeSymbol);

                        if (leftType is null) return null;

                        if (!leftType.GetAttributes().Any(a =>
                                a.AttributeClass?.Name == "ImguiAutoPropertyAttribute"))
                            return null;

                        var memberName = name.Identifier.ValueText;

                        if (leftType.GetMembers(memberName).Any(m => m.IsStatic))
                            return null;

                        var (inferred, showOnly) = InferTypeFromContext(semanticModel, mae);

                        return inferred is null ? null : new Candidate(leftType, memberName, inferred, showOnly);
                    })
                .Where(x => x is not null)! 
                .Collect();

            context.RegisterSourceOutput(memberAccesses, static (spc, list) =>
            {
                
                var groups = list!
                    .GroupBy(c => (c!.Owner, c!.MemberName))
                    .ToArray();
                Dictionary<string,(string properties, string function, string save, string load)> sources = new();
                foreach (var g in groups)
                {
                    var owner = g.Key.Owner!;
                    var member = g.Key.MemberName;
               
                    
                    var distinct =  g.Select(c => c!.InferredType)
                        .Distinct(SymbolEqualityComparer.Default).ToImmutableArray();

                    if (distinct.Length == 0)
                        continue;

                    if (distinct.Length > 1)
                    {
                        var diag = Diagnostic.Create(
                            new DiagnosticDescriptor(
                                id: "IMGUI_AGP001",
                                title: "自动生成成员的类型冲突",
                                messageFormat: $"在 {owner.ToDisplayString()} 上为 {member} 推断出了多个不同类型。",
                                category: "AutoGen",
                                DiagnosticSeverity.Error,
                                isEnabledByDefault: true),
                            Location.None);
                        spc.ReportDiagnostic(diag);
                        continue;
                    }
                    
                    var value = g.Select(c => c!.ShowOnly).Distinct().ToImmutableArray();
                    var showOnly = value.All(i => i);
                    var t = distinct[0];
                    var ns = owner.ContainingNamespace.IsGlobalNamespace
                        ? null
                        : owner.ContainingNamespace.ToDisplayString();
                    var hintName = $"{owner.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)}.AutoGen.g.cs"
                        .Replace('<', '_').Replace('>', '_');
                    if (!sources.ContainsKey(hintName))
                        sources.Add(hintName, ($@"// <auto-generated/>
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using System;

{(ns is null ? "namespace Pkuyo" : $"namespace {ns}")}
{{
partial {(owner.TypeKind == TypeKind.Struct ? "struct" : "class")} {owner.Name}
{{
    private static Dictionary<string,object> _saveDic = new();

    private static string filePath = """";

    private static T ConvertTo<T>(object value)
    {{
        if (value == null || value is DBNull)
            return default(T);

        if (value is T variable)
            return variable;

        if (value is Newtonsoft.Json.Linq.JValue jValue)
            value = jValue.Value;

        return (T)Convert.ChangeType(value, typeof(T));
    }}
    private static bool IsBuiltInType(Type type)
    {{
        return type.IsPrimitive 
               || type == typeof(string) 
               || type == typeof(decimal)
               || type == typeof(DateTime);   
    }}

    static {owner.Name}() 
    {{
        Load();
    }}

    private static void Clean()
    {{
        _saveDic.Clear();
    }}
",@"
    public static partial void Draw ()
    {
",@"
    public static void Save()
    {",$@"
    public static void Load()
    {{
        var dirPath = Path.Combine(Environment.CurrentDirectory, ""_ShadedCanopy"");
        if (!Directory.Exists(dirPath))
            Directory.CreateDirectory(dirPath);
        filePath = Path.Combine(dirPath, ""_Cache_{owner.Name}.json"");
        if(File.Exists(filePath))
            _saveDic = JsonConvert.DeserializeObject<Dictionary<string,object>>(File.ReadAllText(filePath));
"));
                    var (prop, func,save,load) = sources[hintName];
                    var typeName = t!.ToDisplayString();
                    var property = 
                        $@"
    public static {typeName} {member} {{ get; set; }}
";
                    if (!showOnly)
                    {
                        property = $@"
    private static {typeName} _field_{member};
    public static {typeName} {member} 
    {{
        get => _field_{member};
        set 
        {{
            if (_field_{member} == value)
                return;
            _field_{member} = value;
            Save();  
        }}
    }}
";
                        save += $@"
        _saveDic[""{member}""] = _field_{member};
";
                        load += $@"
        if(_saveDic.TryGetValue(""{member}"", out var _value_{member}))
            _field_{member} = ConvertTo<{typeName}>(_value_{member});
";
                    }
                    if (showOnly)
                    {
                        func += $@"
        if (IsBuiltInType({member}.GetType()))
            ImGuiNET.ImGui.Text($""{member}: {{{member}}}"");
        else
            ImGuiNET.ImGui.Text($""{member}: {{Newtonsoft.Json.JsonConvert.SerializeObject({member})}}"");
";
                    }
                    else
                    {


                        var imguiName = typeName switch
                        {
                            "int" => "InputInt",
                            "float" => "InputFloat",
                            "double" => "InputDouble",
                            "string" => "InputText",
                            "bool" => "Checkbox",
                            _ => null
                        };

                        if (imguiName is null)
                        {
                            var diag2 = Diagnostic.Create(
                                new DiagnosticDescriptor(
                                    id: "IMGUI_AGP002",
                                    title: "未知IMGUI控件",
                                    messageFormat: $"在 {owner.ToDisplayString()} 上为 {member} 无法确定合适的IMGUI控件",
                                    category: "AutoGen",
                                    DiagnosticSeverity.Warning,
                                    isEnabledByDefault: true),
                                Location.None);
                            spc.ReportDiagnostic(diag2);
                            continue;
                        }

                        var function = $@"        var _{member} = {member};
        ImGuiNET.ImGui.{imguiName}(""{member}"",ref _{member});
        {member} = _{member};
";
                        func += function;
                    }

                    prop += property;
           
                    sources[hintName] = (prop, func, save, load);
                }

                foreach (var source in sources)
                {
                    var (prop, func,save, load) = source.Value;
                    func += @"
        if(ImGuiNET.ImGui.Button(""Clean Data""))
            Clean();
    }";
                    load +=  @"
    }";
                    save +=  @"
        var value = JsonConvert.SerializeObject(_saveDic);
        File.Delete(filePath);
        File.WriteAllText(filePath, value);
    }";
                    
                    spc.AddSource(source.Key, prop + func + load + save + @"
}
}");
                }
            });
        }

        private static (INamedTypeSymbol? symbol, bool showOnly) InferTypeFromContext(SemanticModel model, MemberAccessExpressionSyntax mae)
        {
            var parent = mae.Parent;

            // int a = XXXX.yyy;
            if (parent is EqualsValueClauseSyntax eq &&
                eq.Parent is VariableDeclaratorSyntax v &&
                v.Parent is VariableDeclarationSyntax vd &&
                vd.Type is not IdentifierNameSyntax { Identifier.ValueText: "var" })
            {
                var type = model.GetTypeInfo(vd.Type).Type as INamedTypeSymbol;
                return (type,false);
            }

            //target = XXXX.yyy;
            if (parent is AssignmentExpressionSyntax assign && assign.Right == mae)
            {
                var leftType = model.GetTypeInfo(assign.Left).Type as INamedTypeSymbol;
                return (leftType,false);
            }
            
            //XXXX.yyy = target;
            if (parent is AssignmentExpressionSyntax assign1 && assign1.Left == mae)
            {
                var rightType = model.GetTypeInfo(assign1.Right).Type as INamedTypeSymbol;
                return (rightType,true);
            }
            
            // Foo(XXXX.yyy)
            if (parent is ArgumentSyntax arg &&
                arg.Parent?.Parent is InvocationExpressionSyntax inv)
            {
                if (model.GetSymbolInfo(inv).Symbol is IMethodSymbol sym)
                {
                    var args = (arg.Parent as ArgumentListSyntax)!.Arguments;
                    var index = args.IndexOf(arg);
                    ITypeSymbol? pType = null;

                    if (index >= 0)
                    {
                        if (index < sym.Parameters.Length)
                            pType = sym.Parameters[index].Type;
                        else if (sym.Parameters.Length > 0 && sym.Parameters[^1].IsParams)
                            pType = ((IArrayTypeSymbol)sym.Parameters[^1].Type).ElementType;
                    }

                    return (pType as INamedTypeSymbol,false);
                }
            }

            // MyType P { get; } = XXXX.yyy;
            if (parent is EqualsValueClauseSyntax eq2)
            {
                var leftSym = model.GetDeclaredSymbol(eq2.Parent!.Parent!) as ISymbol;
                ITypeSymbol? t = leftSym switch
                {
                    IPropertySymbol ps => ps.Type,
                    IFieldSymbol fs => fs.Type,
                    _ => null
                };
                return (t as INamedTypeSymbol,false);
            }

            return (null,false);
        }

        private sealed record Candidate(INamedTypeSymbol Owner, string MemberName, INamedTypeSymbol InferredType, bool ShowOnly);
    }
}
